:test_settings:
  :setting_one: '1'

:logging:
  :log_identifier: => 'ubsafe'
  :log_directory: => './spec/tmp/logs'
  :log_filename_pattern: => 'ubsafe.log'
  :log_level: => :debug

:backups:
  :git1:
    :enabled: true
    :backup_type: :git
    :source_tree: './spec/test_data/sources/git'
    :backup_host: :test1
    :temporary_directory: './spec/tmp'
  # :mysql:
  #   
  # :svn:
  #   
  # :wiki:
:backup_defaults:
  :number_format: '%3d'
  :time_zone_type: 'UTC'  #Only time zone currently supported

:backup_types:
  :git:
    :backup_style: :tar_gz
    :backup_frequency: <%= 1.day %>
    :backup_file_name_template: '%f.%n.tar.gz'
    :backup_retention: 30

:backup_hosts:
  :test:
    :hostname: '10.1.10.52'
    :user_name: 'tflynn'
    :password: 'b3e1r4t1'
    :base_backup_directory: '/Users/tflynn/Everything/Activities/git/ubsafe/spec/tmp/targets'
  :test1:
    :hostname: '192.168.1.100'
    :user_name: 'tracy'
    :password: 'b3e1r4t1'
    :base_backup_directory: '/Users/tracy/Everything/Activities/git/ubsafe/spec/tmp/targets'    
    