:test_settings:
  :setting_one: '1'

:logging:
  :log_identifier: 'ubsafe'
  :log_directory: './spec/logs'
  :log_filename_pattern: 'ubsafe%env%.log' # Specify ENV['UBSAFE_ENV'] to set environment
  :log_level: :debug
  :log_rolling_frequency: 'daily'
  :logs_to_retain: 30

:backups:
  :git_repos:
    :enabled: true
    :backup_name: 'git_repos'   # must be single string, no spaces
    :backup_type: :git
    :source_tree: './spec/test_data/sources/git'
    :backup_host: :test1
    :temporary_directory: './spec/tmp'
  # :mysql:
  #   
  # :svn:
  #   
  # :wiki:
:backup_defaults:
  :number_format: '%d'
  :time_zone: 'UTC'  # UTC is the only time zone currently supported
  :timestamp_format: '%Y%m%d%H%M' # strftime format
  :date_format: '%Y%m%d' # strftime format

:backup_types:
  :git:
    :backup_style: :tar_gz
    :backup_frequency: <%= 1.second %>
    :backup_file_name_template: '%f.tar.gz.%n'
    :backups_to_retain: 3

:backup_hosts:
  :test:
    :hostname: '10.1.10.52'
    :user_name: 'tflynn'
    :password: <%= `cat .password` %>
    :base_backup_directory: '/Users/tflynn/Everything/Activities/git/ubsafe/spec/tmp/targets'
  :test1:
    :hostname: '192.168.1.100'
    :user_name: 'tracy'
    :password: 'b3e1r4t1'
    :base_backup_directory: '/Users/tracy/Everything/Activities/git/ubsafe/spec/tmp/targets'    

:backup_email:
  :enabled: true
  :smtp_host: 'mail.helium.com'
  :smtp_port: 25
  :mail_from: 'devbackups@helium.com'
  :mail_to: 
    - 'tflynn@helium.com'
  :mail_subject_prefix: '[ubsafe] '
