:test_settings:
  :setting_one: '1'

:logging:
  :log_identifier: 'ubsafe'
  :log_directory: '/Users/tracy/Temp/dev/ubsafe/logs'
  :log_filename_pattern: 'ubsafe%env%.log' # Specify ENV['UBSAFE_ENV'] to set environment
  :log_level: :debug
  :log_rolling_frequency: 'daily'
  :logs_to_retain: 30

:backups:
  :ubsafe_repo:
    :enabled: true
    :backup_name: 'ubsafe_repo'   # must be single string, no spaces
    :backup_type: :git
    :source_tree: '/Users/tracy/Temp/dev/ubsafe/source_repos/ubsafe'
    :backup_host: :test1
    :temporary_directory: '/Users/tracy/Temp/dev/ubsafe/tmp'
  :svn_repo:
    :enabled: true
    :backup_name: 'svn_repo'   # must be single string, no spaces
    :backup_type: :svn
    :source_tree: '/Users/tracy/Temp/dev/svn_repo'
    :backup_host: :test1
    :temporary_directory: '/Users/tracy/Temp/dev/ubsafe/tmp'
  :mysql_db:
    :enabled: true
    :backup_name: 'mysql_db'   # must be single string, no spaces
    :backup_type: :mysql
    :source_tree: '/Users/tracy/Temp/dev/mysql'
    :backup_host: :test1
    :temporary_directory: '/Users/tracy/Temp/dev/ubsafe/tmp'
    :mysql_host: 'holly'
    :mysql_username: 'tflynn'
    :mysql_password: <%= `cat .ubsafe_mysqlpassword` %>
    :mysql_database: 'mysql'
  #   
  # :wiki:
:backup_defaults:
  :number_format: '%d'
  :time_zone: 'UTC'  # UTC is the only time zone currently supported
  :timestamp_format: '%Y%m%d%H%M' # strftime format
  :date_format: '%Y%m%d' # strftime format

:backup_types:
  :git:
    :backup_style: :tar_gz
    :backup_frequency: <%= 5.seconds %>
    :backup_file_name_template: '%f.tar.gz.%n'
    :backups_to_retain: 5
    :backup_class: :default
  :svn:
    :backup_style: :tar_gz
    :backup_frequency: <%= 5.seconds %>
    :backup_file_name_template: '%f.tar.gz.%n'
    :backups_to_retain: 5
    :backup_class: 'UBSafe::Commands::SVNBackup'
  :mysql:
    :backup_style: :tar_gz
    :backup_frequency: <%= 5.seconds %>
    :backup_file_name_template: '%f.tar.gz.%n'
    :backups_to_retain: 5
    :backup_class: 'UBSafe::Commands::MySqlBackup'

:backup_hosts:
  :test:
    :hostname: '10.1.10.52'
    :user_name: 'tflynn'
    :password: <%= `cat .ubsafe_password` %>
    :base_backup_directory: '/Users/tflynn/Everything/Activities/git/ubsafe/spec/tmp/targets'
    :bin_dir:
  :test1:
    :hostname: '192.168.1.100'
    :user_name: 'tracy'
    :password: <%= `cat .ubsafe_password` %>
    :base_backup_directory: '/Users/tracy/Temp/dev/ubsafe/backups'
    :bin_dir:    

:backup_email:
  :enabled: false
  :smtp_host: 'mail.helium.com'
  :smtp_port: 25
  :mail_from: 'devbackups@helium.com'
  :mail_to: 
    - 'tflynn@helium.com'
  :mail_subject_prefix: '[ubsafe] '
  :mail_style: :smtp # or :cat_sendmail
